<?php
/**
 * @file
 * Primary module hooks for Xylot Themes V7 General Use Module (GUM) module.
 */
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityStorageInterface;

/**
 * Implements hook_form_alter().
 */
function v7_inline_entity_form_entity_form_alter(array &$entity_form, FormStateInterface &$form_state) {
  // $entity_type = $entity_form['#entity_type'];
  // $ief_id = $entity_form['#ief_id'];

  /// Taxnomy terms ///
  // switch ($entity_type) {

  //   case 'taxonomy_term':
  //     $vocab = $entity_form['#bundle'];

  //     switch ($vocab) {

  //     } // end switch

  //   break;

  // } // end switch
}

/**
 * Implements hook_form_alter().
 *
 * Replaces the "Add media" button text with more appropriate text.
 */
function v7_field_widget_media_library_widget_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $context) {
  /* */
  // $entity = $form_state->getFormObject()->getEntity();
  $title = $form['#title'];

  switch ($title) {

    case 'Other Images':
      $button_text = t('Add additional image(s)');
      break;

    case 'Profile Image':
      $button_text = t('Add profile image');
      break;

    default:
      $button_text = t('Add ' . strtolower($title));

  }

  $form['open_button']['#value'] = $button_text;
}

function v7_preprocess_page(&$variables) {
  if (\Drupal::service('router.admin_context')->isAdminRoute()) {
    $variables['#attached']['library'][] = 'v7/admin_overrides';
  }
}
