# Schema for the configuration files of the Xylot Themes V7 General Use Module (GUM) module.
v7.settings:
  type: config_object
  label: 'Xylot Themes V7 General Use Module (GUM) settings'
  mapping:
    example:
      type: string
      label: 'Example'
